#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Sitana.Framework.Resource", IsApplication=false)]

namespace Sitana.Framework
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f010016
			public static int appTheme = 2130771990;
			
			// aapt resource value: 0x7f01001d
			public static int buyButtonAppearance = 2130771997;
			
			// aapt resource value: 0x7f01001a
			public static int buyButtonHeight = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public static int buyButtonText = 2130771996;
			
			// aapt resource value: 0x7f01001b
			public static int buyButtonWidth = 2130771995;
			
			// aapt resource value: 0x7f010007
			public static int cameraBearing = 2130771975;
			
			// aapt resource value: 0x7f010008
			public static int cameraTargetLat = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int cameraTargetLng = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public static int cameraTilt = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public static int cameraZoom = 2130771979;
			
			// aapt resource value: 0x7f010005
			public static int circleCrop = 2130771973;
			
			// aapt resource value: 0x7f010017
			public static int environment = 2130771991;
			
			// aapt resource value: 0x7f010019
			public static int fragmentMode = 2130771993;
			
			// aapt resource value: 0x7f010018
			public static int fragmentStyle = 2130771992;
			
			// aapt resource value: 0x7f010004
			public static int imageAspectRatio = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int imageAspectRatioAdjust = 2130771971;
			
			// aapt resource value: 0x7f01000c
			public static int liteMode = 2130771980;
			
			// aapt resource value: 0x7f010006
			public static int mapType = 2130771974;
			
			// aapt resource value: 0x7f010020
			public static int maskedWalletDetailsBackground = 2130772000;
			
			// aapt resource value: 0x7f010022
			public static int maskedWalletDetailsButtonBackground = 2130772002;
			
			// aapt resource value: 0x7f010021
			public static int maskedWalletDetailsButtonTextAppearance = 2130772001;
			
			// aapt resource value: 0x7f01001f
			public static int maskedWalletDetailsHeaderTextAppearance = 2130771999;
			
			// aapt resource value: 0x7f010024
			public static int maskedWalletDetailsLogoImageType = 2130772004;
			
			// aapt resource value: 0x7f010023
			public static int maskedWalletDetailsLogoTextColor = 2130772003;
			
			// aapt resource value: 0x7f01001e
			public static int maskedWalletDetailsTextAppearance = 2130771998;
			
			// aapt resource value: 0x7f01000d
			public static int uiCompass = 2130771981;
			
			// aapt resource value: 0x7f010015
			public static int uiMapToolbar = 2130771989;
			
			// aapt resource value: 0x7f01000e
			public static int uiRotateGestures = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public static int uiScrollGestures = 2130771983;
			
			// aapt resource value: 0x7f010010
			public static int uiTiltGestures = 2130771984;
			
			// aapt resource value: 0x7f010011
			public static int uiZoomControls = 2130771985;
			
			// aapt resource value: 0x7f010012
			public static int uiZoomGestures = 2130771986;
			
			// aapt resource value: 0x7f010013
			public static int useViewLifecycle = 2130771987;
			
			// aapt resource value: 0x7f010014
			public static int zOrderOnTop = 2130771988;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070009
			public static int common_action_bar_splitter = 2131165193;
			
			// aapt resource value: 0x7f070000
			public static int common_signin_btn_dark_text_default = 2131165184;
			
			// aapt resource value: 0x7f070002
			public static int common_signin_btn_dark_text_disabled = 2131165186;
			
			// aapt resource value: 0x7f070003
			public static int common_signin_btn_dark_text_focused = 2131165187;
			
			// aapt resource value: 0x7f070001
			public static int common_signin_btn_dark_text_pressed = 2131165185;
			
			// aapt resource value: 0x7f070008
			public static int common_signin_btn_default_background = 2131165192;
			
			// aapt resource value: 0x7f070004
			public static int common_signin_btn_light_text_default = 2131165188;
			
			// aapt resource value: 0x7f070006
			public static int common_signin_btn_light_text_disabled = 2131165190;
			
			// aapt resource value: 0x7f070007
			public static int common_signin_btn_light_text_focused = 2131165191;
			
			// aapt resource value: 0x7f070005
			public static int common_signin_btn_light_text_pressed = 2131165189;
			
			// aapt resource value: 0x7f070017
			public static int common_signin_btn_text_dark = 2131165207;
			
			// aapt resource value: 0x7f070018
			public static int common_signin_btn_text_light = 2131165208;
			
			// aapt resource value: 0x7f07000f
			public static int wallet_bright_foreground_disabled_holo_light = 2131165199;
			
			// aapt resource value: 0x7f07000a
			public static int wallet_bright_foreground_holo_dark = 2131165194;
			
			// aapt resource value: 0x7f070010
			public static int wallet_bright_foreground_holo_light = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public static int wallet_dim_foreground_disabled_holo_dark = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public static int wallet_dim_foreground_holo_dark = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public static int wallet_dim_foreground_inverse_disabled_holo_dark = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public static int wallet_dim_foreground_inverse_holo_dark = 2131165197;
			
			// aapt resource value: 0x7f070014
			public static int wallet_highlighted_text_holo_dark = 2131165204;
			
			// aapt resource value: 0x7f070013
			public static int wallet_highlighted_text_holo_light = 2131165203;
			
			// aapt resource value: 0x7f070012
			public static int wallet_hint_foreground_holo_dark = 2131165202;
			
			// aapt resource value: 0x7f070011
			public static int wallet_hint_foreground_holo_light = 2131165201;
			
			// aapt resource value: 0x7f070015
			public static int wallet_holo_blue_light = 2131165205;
			
			// aapt resource value: 0x7f070016
			public static int wallet_link_text_light = 2131165206;
			
			// aapt resource value: 0x7f070019
			public static int wallet_primary_text_holo_light = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public static int wallet_secondary_text_holo_dark = 2131165210;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int common_signin_btn_text_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int ic_plusone_medium_off_client = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int ic_plusone_small_off_client = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int ic_plusone_standard_off_client = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public static int ic_plusone_tall_off_client = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int powered_by_google_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int powered_by_google_light = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public static int adjust_height = 2131099650;
			
			// aapt resource value: 0x7f060001
			public static int adjust_width = 2131099649;
			
			// aapt resource value: 0x7f060012
			public static int book_now = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public static int buyButton = 2131099660;
			
			// aapt resource value: 0x7f060011
			public static int buy_now = 2131099665;
			
			// aapt resource value: 0x7f060010
			public static int buy_with_google = 2131099664;
			
			// aapt resource value: 0x7f060014
			public static int classic = 2131099668;
			
			// aapt resource value: 0x7f060013
			public static int donate_with_google = 2131099667;
			
			// aapt resource value: 0x7f060015
			public static int grayscale = 2131099669;
			
			// aapt resource value: 0x7f060007
			public static int holo_dark = 2131099655;
			
			// aapt resource value: 0x7f060008
			public static int holo_light = 2131099656;
			
			// aapt resource value: 0x7f060006
			public static int hybrid = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public static int match_parent = 2131099662;
			
			// aapt resource value: 0x7f060016
			public static int monochrome = 2131099670;
			
			// aapt resource value: 0x7f060000
			public static int none = 2131099648;
			
			// aapt resource value: 0x7f060003
			public static int normal = 2131099651;
			
			// aapt resource value: 0x7f060009
			public static int production = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public static int sandbox = 2131099658;
			
			// aapt resource value: 0x7f060004
			public static int satellite = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public static int selectionDetails = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public static int strict_sandbox = 2131099659;
			
			// aapt resource value: 0x7f060005
			public static int terrain = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public static int wrap_content = 2131099663;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public static int google_play_services_version = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f030000
			public static int gtm_analytics = 2130903040;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public static int accept = 2131034114;
			
			// aapt resource value: 0x7f050009
			public static int common_android_wear_notification_needs_update_text = 2131034121;
			
			// aapt resource value: 0x7f050016
			public static int common_android_wear_update_text = 2131034134;
			
			// aapt resource value: 0x7f050014
			public static int common_android_wear_update_title = 2131034132;
			
			// aapt resource value: 0x7f050012
			public static int common_google_play_services_enable_button = 2131034130;
			
			// aapt resource value: 0x7f050011
			public static int common_google_play_services_enable_text = 2131034129;
			
			// aapt resource value: 0x7f050010
			public static int common_google_play_services_enable_title = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public static int common_google_play_services_error_notification_requested_by_msg = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public static int common_google_play_services_install_button = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public static int common_google_play_services_install_text_phone = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public static int common_google_play_services_install_text_tablet = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public static int common_google_play_services_install_title = 2131034124;
			
			// aapt resource value: 0x7f05001a
			public static int common_google_play_services_invalid_account_text = 2131034138;
			
			// aapt resource value: 0x7f050019
			public static int common_google_play_services_invalid_account_title = 2131034137;
			
			// aapt resource value: 0x7f05000a
			public static int common_google_play_services_needs_enabling_title = 2131034122;
			
			// aapt resource value: 0x7f050018
			public static int common_google_play_services_network_error_text = 2131034136;
			
			// aapt resource value: 0x7f050017
			public static int common_google_play_services_network_error_title = 2131034135;
			
			// aapt resource value: 0x7f050007
			public static int common_google_play_services_notification_needs_installation_title = 2131034119;
			
			// aapt resource value: 0x7f050008
			public static int common_google_play_services_notification_needs_update_title = 2131034120;
			
			// aapt resource value: 0x7f050006
			public static int common_google_play_services_notification_ticker = 2131034118;
			
			// aapt resource value: 0x7f05001b
			public static int common_google_play_services_unknown_issue = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public static int common_google_play_services_unsupported_text = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public static int common_google_play_services_unsupported_title = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public static int common_google_play_services_update_button = 2131034142;
			
			// aapt resource value: 0x7f050015
			public static int common_google_play_services_update_text = 2131034133;
			
			// aapt resource value: 0x7f050013
			public static int common_google_play_services_update_title = 2131034131;
			
			// aapt resource value: 0x7f050021
			public static int common_open_on_phone = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public static int common_signin_button_text = 2131034143;
			
			// aapt resource value: 0x7f050020
			public static int common_signin_button_text_long = 2131034144;
			
			// aapt resource value: 0x7f050005
			public static int create_calendar_message = 2131034117;
			
			// aapt resource value: 0x7f050004
			public static int create_calendar_title = 2131034116;
			
			// aapt resource value: 0x7f050003
			public static int decline = 2131034115;
			
			// aapt resource value: 0x7f050023
			public static int library_name = 2131034147;
			
			// aapt resource value: 0x7f050001
			public static int store_picture_message = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int store_picture_title = 2131034112;
			
			// aapt resource value: 0x7f050022
			public static int wallet_buy_button_place_holder = 2131034146;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public static int Theme_IAPTheme = 2130968576;
			
			// aapt resource value: 0x7f040003
			public static int WalletFragmentDefaultButtonTextAppearance = 2130968579;
			
			// aapt resource value: 0x7f040002
			public static int WalletFragmentDefaultDetailsHeaderTextAppearance = 2130968578;
			
			// aapt resource value: 0x7f040001
			public static int WalletFragmentDefaultDetailsTextAppearance = 2130968577;
			
			// aapt resource value: 0x7f040004
			public static int WalletFragmentDefaultStyle = 2130968580;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public static int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public static int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public static int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public static int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public static int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public static int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[]
			{
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 1
			public static int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public static int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public static int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public static int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public static int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public static int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public static int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public static int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public static int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public static int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public static int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public static int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public static int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public static int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public static int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public static int MapAttrs_zOrderOnTop = 14;
			
			public static int[] WalletFragmentOptions = new int[]
			{
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public static int WalletFragmentOptions_appTheme = 0;
			
			// aapt resource value: 1
			public static int WalletFragmentOptions_environment = 1;
			
			// aapt resource value: 3
			public static int WalletFragmentOptions_fragmentMode = 3;
			
			// aapt resource value: 2
			public static int WalletFragmentOptions_fragmentStyle = 2;
			
			public static int[] WalletFragmentStyle = new int[]
			{
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004};
			
			// aapt resource value: 3
			public static int WalletFragmentStyle_buyButtonAppearance = 3;
			
			// aapt resource value: 0
			public static int WalletFragmentStyle_buyButtonHeight = 0;
			
			// aapt resource value: 2
			public static int WalletFragmentStyle_buyButtonText = 2;
			
			// aapt resource value: 1
			public static int WalletFragmentStyle_buyButtonWidth = 1;
			
			// aapt resource value: 6
			public static int WalletFragmentStyle_maskedWalletDetailsBackground = 6;
			
			// aapt resource value: 8
			public static int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 8;
			
			// aapt resource value: 7
			public static int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 7;
			
			// aapt resource value: 5
			public static int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 5;
			
			// aapt resource value: 10
			public static int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 10;
			
			// aapt resource value: 9
			public static int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
			
			// aapt resource value: 4
			public static int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
